vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        festival:
            uri_prefix: /images/festival
            upload_destination: '%kernel.project_dir%/public/images/festival'
