version: "3.8"
services:

  db: 
    image: postgres:14.2
    container_name: db_docker_symfony
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: festinb
      POSTGRES_USER: postgres
      POSTGRES_INITDB_ARGS: "--data-checksums"
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - dev

  adminer:
    image: adminer:4.8.1
    container_name: adminer_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: nette
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8000:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./festinb:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: