controllers_back:
    resource: ../src/Controller/Back
    type: annotation
    prefix: admin
    name_prefix: app_back_

controllers_front:
    resource: ../src/Controller/Front
    type: annotation
    name_prefix: app_front_

controllers_api:
    resource: ../src/Controller/Api
    type: annotation
    prefix: api
    name_prefix: api_

kernel:
    resource: ../src/Kernel.php
    type: annotation
